shot=1;
shotCount=15;
allD=false;
shotLengthNext = 60*13;
shotTime = shotLengthNext;

instance_create(0, 0, objBlue);
instance_create(0, 0, visBlack);
instance_create(0, 0, objRush);
instance_create(0, 0, objReach);
instance_create(0, 0, objHold);
instance_create(0, 0, objLanding);
instance_create(0, 0, objLanded);
instance_create(0, 0, objReptile);
instance_create(0, 0, objShook);
instance_create(0, 0, objGround0);
instance_create(0, 0, objAtmo);
instance_create(0, 0, objRepCut00);
instance_create(0, 0, objRepCut01);
instance_create(0, 0, objRepCut1);
instance_create(0, 0, objRepCut2);
instance_create(0, 0, objRepCut3);
instance_create(0, 0, objPcut0);
instance_create(0, 0, objPcut1);
instance_create(0, 0, objPcut3);
instance_create(0, 0, objBranched);
instance_create(0, 0, objVisEnd);
