shot=1;
shotCount=15;
allD=false;
shotLength = 60*5;
shotTime = shotLength;

instance_create(0, 0, objBlue);
instance_create(0, 0, objRush);
instance_create(0, 0, objReach);
instance_create(0, 0, objHold);
instance_create(0, 0, objLanding);
instance_create(0, 0, objLanded);
instance_create(0, 0, objReptile);
instance_create(0, 0, objGround0);
instance_create(0, 0, objAtmo);
instance_create(0, 0, objRepCut00);
instance_create(0, 0, objRepCut01);
instance_create(0, 0, objRepCut1);
instance_create(0, 0, objRepCut2);
instance_create(0, 0, objRepCut3);
instance_create(0, 0, objPcut0);
instance_create(0, 0, objPcut1);
instance_create(0, 0, objPcut3);
instance_create(0, 0, objBranched);
instance_create(0, 0, objVisEnd);
